# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('company', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=10)),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=10)),
                ('e_mail', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_planner_app.EmergencyContact')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='End Date')),
                ('load_in', models.DateTimeField(auto_now_add=True, verbose_name='Load In')),
                ('load_out', models.DateTimeField(auto_now_add=True, verbose_name='Load Out')),
                ('venue_name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('zip', models.CharField(max_length=5)),
            ],
        ),
    ]
