# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_for', to='event_planner_app.EmergencyContact'),
        ),
    ]
