# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner_app', '0002_auto_20170804_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 33, 13, 520294, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 33, 13, 520810, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='load_in',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 33, 13, 520840, tzinfo=utc), verbose_name='Load In'),
        ),
        migrations.AlterField(
            model_name='event',
            name='load_out',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 33, 13, 520861, tzinfo=utc), verbose_name='Load Out'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 33, 13, 520784, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
