# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner_app', '0003_auto_20170804_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 34, 24, 789383, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 34, 24, 789872, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='load_in',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 34, 24, 789892, tzinfo=utc), verbose_name='Load In'),
        ),
        migrations.AlterField(
            model_name='event',
            name='load_out',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 34, 24, 789914, tzinfo=utc), verbose_name='Load Out'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 1, 34, 24, 789846, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
